### ISSUE TITLE
Uninstallation of Packages

### ISSUE THREAD

**Issue by Vi1i** [kewlfft/ansible-aur#20]
I think a feature to be able to uninstall packages would be great, currently I am having to use a command or shell to do so.

With that said, I now have a heavy requirement of ansible-aur, so I would be interested in contributing if it is possible.

**Comment by kewlfft** [comment]
There is the pacman module to uninstall packages, why should it duplicate the function?

**Comment by Vi1i** [comment]
Hmm I see your point, I didn't think of that for some reason.
