### ISSUE TITLE
Option to show build progress

### ISSUE THREAD

**Issue by victorbrca** [kewlfft/ansible-aur#26]
I'm running 'ansible-aur' to rebuild VM images, and I'm noticing that sometimes it looks like the install hangs (which could be just taking long to compile), but I have no visibility of what's going in the background. 

Is there an option to show the build/install progress? I have tried `ansible-playbook -vvv` but that does not show build progress. 

Thanks!

**Comment by kewlfft** [comment]
Thanks for your question, there is no specific option to show the progress. 
Then like for any module you could see the output after completion, something like `register: progress` and `- debug: msg="{{ progress.stdout }}"`
