### ISSUE TITLE
is ansible-aur-git up to date?

### ISSUE THREAD

**Issue by tabroughton** [kewlfft/ansible-aur#27]
Hi @kewlfft and @panchoh just thought I'd you both about this because of issue [#5]

I was trying to simplify some ansible workfIow and thought it might be easier and possibly more stable to install ansible-aur via pacman instead of cloning the git repo and I  wondered if the [ansible-aur-git ](https://aur.archlinux.org/packages/ansible-aur-git) is up to date? I'm assuming not as the last updated date is quite a while ago...  if not what's the advice on requesting it to be updated please? 

Also, if you feel it not necessary and that cloning is just as easy and stable then do let me know - I'd happily use either route it's just the readme in this project presents both options and I'm unsure of best practices (I'm just getting to grips with arch and ansible)

**Comment by kewlfft** [comment]
It is best to use the package maintained by @panchoh 
This is a [VCS package](https://wiki.archlinux.org/index.php/VCS_package_guidelines), the PKGBUILD does not need to be updated to retrieve the latest version.

**Comment by panchoh** [comment]
Hi, folks.
I've just updated `ansible-aur-git` base git version, if only to show potential users that the package is still current and being maintained.
Happy ansibling!

**Comment by tabroughton** [comment]
Fab thanks both, I've learnt something new today.  I can see when I view the package in aur there's a link to the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ansible-aur-git).  This is useful knowledge about aur I didn't know.  Thanks for the pointers and help.
