### ISSUE TITLE
Upgrade cannot be used with this option. - maybe my fault ...

### ISSUE THREAD

**Issue by herrmie** [kewlfft/ansible-aur#31]
Hello,
I am new in ansible, but want to use your role.
I have following playbook:

    ---
    - name: Update the AUR
      hosts: localhost
      become: yes
      become_user: aur_builder
    
      roles:
        - kewlfft.aur
    
      tasks:
        - aur: upgrade=yes```

And the error is: Upgrade cannot be used with this option.
But if I have a look in your aur.py:

`    if params['upgrade'] and (params['name'] or params['skip_installed'] or use == 'makepkg'):
        module.fail_json(msg="Upgrade cannot be used with this option.")`

It should be work as you can see the variable:

    "module_args": {
            "aur_only": false,
            "ignore_arch": false,
            "name": null,
            "skip_installed": false,
            "skip_pgp_check": false,
            "upgrade": true,
            "use": "auto"

Thanks for help and greets,
herrmie

**Comment by kewlfft** [comment]
Hi this works for me:
~~~
- name: AUR upgrade
  aur: upgrade=yes aur_only=yes use=yay
  become_user: kewlfft
  environment:
    XDG_CACHE_HOME: /tmp
  register: aur_result
~~~

**Comment by herrmie** [comment]
Hello,
okay with yay it is working. But with makepkg it is not working.
But it shoud, am I right?
Like this:

    - name: AUR upgrade
      aur: upgrade=yes aur_only=yes use=makepkg
      become_user: kewlfft
      environment:
        XDG_CACHE_HOME: /tmp
      register: aur_result

**Comment by kewlfft** [comment]
makepkg does not upgrade
