### ISSUE TITLE
ignore_errors

### ISSUE THREAD

**Issue by eoli3n** [kewlfft/ansible-aur#33]
AUR package install fails frequently, i want to be able to continue the loop if a package fails to install.

Using ``ignore_errors`` at the task level make the task to skip if an error occurs, but every aur packages after the failling one are skipped.
Is there a way to add an ``ignore_errors`` option ?

**Comment by kewlfft** [comment]
I don't think we are going to change the way ansible loops or the helper you use deal with errors, if there is a helper option that does what you want we can think about adding this option, but that is about it.

**Comment by eoli3n** [comment]
But i don't use ``loop:`` but ``name:\n-package1\npackage2``. I was thinking that this kind of loop if managed by the module itself, am i wrong ?
https://github.com/eoli3n/arch-config/blob/master/ansible/roles/desktop/tasks/main.yml#L73

**Comment by kewlfft** [comment]
do you have an example of module with the desired behavior (like the _pacman_ module or other) and I can look into it. Otherwise, iff this is the way official packages behave in case of error, we should stick to it.

**Comment by eoli3n** [comment]
I don't have any example. AUR are a special usecase, because it is designed to fail. Anyway, thx for your answer
