### ISSUE TITLE
Add ability to pass arbitrary arguments on install and upgrade

### ISSUE THREAD

**Issue by chpatton013** [kewlfft/ansible-aur#38]
I've seen some AUR packages do weird things with their `prepare` hooks, which require some TTY interaction to resolve. For this packages I generally just want to run `makepkg` with the `--noprepare` flag. Various AUR-helpers have options to pass arbitrary flags onto `makepkg` (such as `yay`, which uses `--mflags`). It would be nice to be able to pass flags to the helper directly, or to `makepkg` using whichever mechanism the helper provides.

So I guess I'm asking for one (or both, preferably) of the following features:
* An additional argument `use_args` that takes a list of string arguments to pass to the helper in-use. This should only be allowed when `use` is set to something other than `auto`.
* An additional argument `makepkg_args` that takes a list of string arguments to pass to `makepkg` using whichever mechanism the active helper supports. This should be incompatible with helpers that don't support this mechanism.

If you're amicable to either of these features, I would be happy to implement them. Just let me know what your thoughts are.

**Comment by kewlfft** [comment]
`use_args` seems like a good idea, we can start with that as it covers your needs and potentially other needs. Please go ahead.

**Comment by chpatton013** [comment]
Just a quick check-in here. I haven't been able to start this until today, and I'm also going to be adding some unit tests for basic functionality. The patch is going to be a bit bigger than just threading a simple arg through since I'll need to do some minor work to make the tests easier to write.
