### ISSUE TITLE
Role name kewlfft.aur does not match ``^[a-z][a-z0-9_]+$`` pattern

### ISSUE THREAD

**Issue by luizribeiro** [kewlfft/ansible-aur#44]
When running `ansible-lint` against my playbook that relies on the role `kewlfft.aur` installed from ansible galaxy, I get this error:

```
$ ansible-lint ec2.yaml
[106] Role name kewlfft.aur does not match ``^[a-z][a-z0-9_]+$`` pattern
../../../.ansible/roles/kewlfft.aur/meta/main.yml:1
galaxy_info:
```

Should we rename this role so it passes `ansible-lint`?

**Comment by kewlfft** [comment]
I don't use Ansible galaxy, what should we rename into what in order to pass this test?

**Comment by luizribeiro** [comment]
Probably `kewlfft_aur`?

**Comment by kewlfft** [comment]
ok let me know precisely what I need to change and where as I don't use neither _galaxy_ nor `ansible-lint`

**Comment by luizribeiro** [comment]
I think this was actually fixed on the `ansible-lint` side. I'm not seeing issues anymore.

Sorry for the noise, thanks for replying though.
