### ISSUE TITLE
Add ability to remove packages, with state: absent

### ISSUE THREAD

**Issue by TheNerdyHamster** [kewlfft/ansible-aur#47]
This is a really use full module, after they removed the `yay` builtin module.

One thing I have been missing is `state: absent`. To remove package with all of the supported install methods.

The only way that it might be possible with is the `extra_args` option. (haven't tested).

**Comment by kewlfft** [comment]
why don't you use the pacman module for this?

**Comment by TheNerdyHamster** [comment]
I totally forgot that the pacman module worked for that.
But a absent state would be useful to keep an consistent way of managing packages without using dif modules.

**Comment by kewlfft** [comment]
I recommend using the official _pacman_ module whenever it fits the need rather than any of us spending time to develop something that already exists. I don't think the multiplication of modules and forks is useful.
