### ISSUE TITLE
Add Paru as a helper

### ISSUE THREAD

**Issue by nekwebdev** [kewlfft/ansible-aur#51]
New cool kid on the block, should be the same flags as yay.
I can do a PR for it if you want?

btw thanks for that project, really helpful.

**Comment by kewlfft** [comment]
Yes that’s a good idea, a PR would be appreciated

**Comment by nekwebdev** [comment]
I am close to starting my install over (gotta love starting fresh and ansible ahah) with my new config and will add paru as the first helper and make sure it works as expected.

Again your project was a great help as I could simply pick and choose what I needed. I think I changed a few things here and there so might do more PRs if they are relevant changes for everyone.
