### ISSUE TITLE
getting temporary directory problem

### ISSUE THREAD

**Issue by pakyrs** [kewlfft/ansible-aur#59]
Hi there, 

I am getting:

```
TASK [aur] *********************************************************************
ok: [local[WARNING]:host]
 Unable to use /home/aur_builder/.ansible/tmp as temporary directory,
failing back to system: [Errno 13] Permission denied: '/home/aur_builder'
```

My ansible setup is this [one](https://github.com/pakyrs/ansible-pull)

I have one task setting up the aur_builder user
`/ansible-pull/roles/common/tasks/aur_user.yml`

and another testing the packages:
`ansible-pull/roles/common/tasks/AUR.yml`

Is this because I am getting root privileges from the start?? How can I get this to work.

Thanks

P

**Comment by gotmax23** [comment]
Change [this line](https://github.com/pakyrs/ansible-pull/blob/2abdd56268495d949522a2bc76a133fc81dc8bd0/roles/common/tasks/aur_user.yml#L4) from `create_home: no` to `create_home: yes`.

**Comment by pakyrs** [comment]
Thanks, now I get greeted with this:

```
TASK [aur] *********************************************************************
[WARNING]: Module remote_tmp /home/aur_builder/.ansible/tmp did not exist and
was created with a mode of 0700, this may cause issues when running as another
user. To avoid this, create the remote_tmp dir with the correct permissions
manually
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "env LC_ALL=C LANGUAGE=C yay -S --noconfirm --needed --cleanafter package_name", "msg": " -> Could not find all required packages:\n\tpackage_name (Target)", "rc": 1, "stderr": " -> Could not find all required packages:\n\tpackage_name (Target)\n", "stderr_lines": [" -> Could not find all required packages:", "\tpackage_name (Target)"], "stdout": "", "stdout_lines": []}
...ignoring
```

Am I doing this wrong? If my ansible playbook gets elevated at first to perfom tasks, when it gets to the aur module, it should just use the aur_builder user created.

Thanks

P

**Comment by gotmax23** [comment]
Now, it seems like it is working correctly. Your problem is that there is no package called `package_name`.

**Comment by adamantike** [comment]
Should this be fixed, or at least explained a little bit, in the project's Readme? As its example uses `create_home: no` to create the `aur_builder` user, since https://github.com/kewlfft/ansible-aur/commit/d05e0bc9797b3b13cd537ee0a38ba363dca78d6d
