### ISSUE TITLE
update_cache is an unsupported parameter

### ISSUE THREAD

**Issue by DMNh** [kewlfft/ansible-aur#65]
When using the `update_cache` parameter as described in the README, I get the following error from Ansible:

    fatal: [hostname]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (kewlfft.aur.aur) module: update_cache. Supported parameters include: use, extra_args, name, upgrade, ignore_arch, state, skip_pgp_check, aur_only, local_pkgbuild."}

I've tested with the version installed by ansible-galaxy and the one from the AUR and both have the same issue. It looks like `update_cache` was added 13 days ago and the last release was on the 4th September so I'm guessing the README is just ahead of the current release?

**Comment by kewlfft** [comment]
that's correct this has not been released yet

**Comment by gotmax23** [comment]
The AUR package now includes the `README` file in /usr/share/doc, so you can look at that to ensure that you are looking at the documentation for the version you have installed as opposed to the unreleased development version.
