### ISSUE TITLE
Ansible 6.0 incompatibility  

### ISSUE THREAD

**Issue by mum-courses** [kewlfft/ansible-aur#75]
After upgrading to the latest ansible version on Archlinux the following stopped working:
```ansible-galaxy collection install kewlfft.aur```

Output: 
```Error! failed to deploy packaging, check that a supported version is installed```

The issue is reproducible on a fresh ArchLinux installation with the latest ansible installed (6.0.0.0-1).

Expected:
Install the collection

**Comment by gotmax23** [comment]
This is not a problem with this collection. It's a problem with Arch's ansible-core package. It's missing a dependency on python-packaging. You can temporarily fix this issue by installing that package. You should also file a bug for Arch's ansible-core package.

**Comment by mum-courses** [comment]
@gotmax23  Thank you so much. You're totally right. Issue is fixed after installing the missing dependency indeed. 
I'll file a bug there as suggested.
