### ISSUE TITLE
Make skip_installed default to true

### ISSUE THREAD

**Issue by JamieMagee** [kewlfft/ansible-aur#9]
I can't see a good reason to reinstall packages when it's not required (`*-git`, `*-hg`, `*-svn`, etc. packages aside). [`ansible-lint`](https://github.com/willthames/ansible-lint) even has [a rule](https://github.com/willthames/ansible-lint/blob/master/lib/ansiblelint/rules/CommandHasChangesCheckRule.py) against this

> Commands should not change things if nothing needs doing

**Comment by kewlfft** [comment]
This is called idempotence and this is strongly recommended for any ansible action. Feel free to propose a fix if you can.

**Comment by kewlfft** [comment]
This is called [indempotence](https://en.wikipedia.org/wiki/Idempotence) and this is the recommended behaviour for any _ansible_ commands. I think your proposal makes sense. I am not going to make a difference depending on the package so this is going to be `skip_installed` for all, is this ok ?

**Comment by JamieMagee** [comment]
Fair enough. I would be happy with just setting `skip_installed` to True by default. I just thought that the extra control might be more useful for some users.

I've sent out another PR with this change.

**Comment by kewlfft** [comment]
I opened the [following issue](https://github.com/ansible/ansible/issues/42445) after review of the `pacman.py` code

**Comment by djagoo** [comment]
I think using the state parameter like in pacman module would be the best option.
